dependencies:
  async: 2.12.0
  characters: 1.3.1
  collection: 1.19.1
  convert: 3.1.2
  crypto: 3.0.6
  csslib: 1.0.2
  file: 7.0.1
  fixnum: 1.1.1
  glob: 2.1.2
  html: 0.15.5
  http: 1.2.2
  http2: 2.3.0
  http_multi_server: 3.2.1
  intl: 0.20.1
  io: 1.0.4
  json_rpc_2: 3.0.3
  json_serializable: 6.9.0
  logging: 1.3.0
  markdown: 7.2.2
  oauth2: 2.0.3
  path: 1.9.1
  pool: 1.5.1
  shelf: 1.4.2
  stack_trace: 1.12.0
  web: 1.1.0
  web_socket: 0.1.6
  web_socket_channel: 3.0.1


description: "Data Interchange Format Implementations"

dev_dependencies:
  build_runner: 2.4.13
  build_web_compilers: 4.0.11
  file_testing: 3.0.2
  lints: 5.0.0
  shelf_test_handler: 2.0.2
  test: 1.25.9
  webdriver: 3.0.4

environment:
  sdk: '>=3.0.0 <=6.0.0'

name: data_interchange
version: 0.2.0
