apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: minio-operator
  name: minio-operator
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: minio-operator
