name: Go

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.2.0
      with:
        go-version: '1.23'

    - name: Build Package
      run: cd ./server && go mod tidy && cd ../ && GOOS=linux GOARCH=amd64 go build -o ./binary/htdinet ./server/source/main.go
